---
title: "Cancer Drug/Gene Vulnerability Dashboard"
author: "Nicholas Wang"
date: "3/16/2020"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tidyverse);
library(readxl);
library(glmnet);
library(ggplot2);
knitr::opts_chunk$set(echo = FALSE);
```

```{r data, cache=TRUE, include=FALSE}
# Import GDSC2 drug data
df.drug <- read_excel('../data/GDSC2_fitted_dose_response_15Oct19.xlsx') %>% 
  select(DRUG_NAME, COSMIC_ID, LN_IC50) %>% 
  distinct(DRUG_NAME, COSMIC_ID, .keep_all = TRUE) %>% 
  pivot_wider(names_from = DRUG_NAME, values_from = LN_IC50) %>% 
  select(names(.)[1], sort(names(.)));

# Import Broad CRISPR data
df.gene <- read_csv('../data/Achilles_gene_effect.csv') %>% 
  drop_na();
names(df.gene) <- sub(' .*', '', names(df.gene));

# Cell line info
df.sample <- read_csv('../data/sample_info.csv', col_types = cols(additional_info = col_character())) %>% 
  select(DepMap_ID, stripped_cell_line_name, COSMIC_ID);
```

Sidebar {.sidebar}
---------------------------------------------------------------------------------------------------
```{r}
selectInput(
  inputId = 'drug',
  label = 'Drug',
  choices = colnames(df.drug)[-1],
  selected = 'Venetoclax'
  );

selectizeInput(
  inputId = 'gene',
  label = 'Gene',
  choices = colnames(df.gene)[-1],
  selected = 'BCL2',
  options = list(maxOptions = 20000)
  );
```

Row {data-height=400}
---------------------------------------------------------------------------------------------------
### Multiple Regression Fit Summary {data-width=400}
```{r}
tableOutput('fit');
```

Row {data-height=1200}
---------------------------------------------------------------------------------------------------
### Top 10 Genes Ordered By Multiple Regression Betas {data-width=200}
```{r}
tableOutput('betas');
```

### Top 10 Genes Ordered By Correlation {data-width=200}
```{r}
tableOutput('all.cors');
```

### Coefficients Ordered By Betas {data-width=400}
```{r}
plotOutput('betas.plot', width = '500px');
```

### Coefficients Ordered By Correlation {data-width=400}
```{r}
plotOutput('betas.plot2', width = '500px');
```

Row {data-height=1600}
---------------------------------------------------------------------------------------------------
### Drug ~ Gene Scatter
```{r}
plotOutput('scatter');
```

### LASSO Lambda Cross-Validation
```{r}
plotOutput('cvfit');
```

```{r context = 'server'}
lambdas <- 10^seq(2, -2, by = -0.1);

df.drug.1 <- reactive({
  merge(df.sample, select(df.drug, COSMIC_ID, input$drug), by = 'COSMIC_ID', all.y = TRUE) %>%
    merge(df.gene, by.x = 'DepMap_ID', by.y = 'X1') %>%
    filter(!is.na(input$drug)) %>%
    drop_na() %>%
    as_tibble()
  });

cvfit <- reactive({
  cv.glmnet(
    as.matrix(df.drug.1()[-(1:4)]),
    pull(df.drug.1(), input$drug),
    alpha = 1,
    lambda = lambdas
    );
  });

output$cvfit <- renderPlot({
  plot(cvfit());
  });

fit.min <- reactive({
  glmnet(
    as.matrix(df.drug.1()[-(1:4)]),
    pull(df.drug.1(), input$drug),
    alpha = 1,
    lambda = cvfit()$lambda.min
    );
  });

output$fit <- renderTable({
  print(fit.min());
});

betas.cor <- reactive({
  betas <- coef(fit.min()) %>%
    as.matrix() %>%
    as.data.frame() %>%
    rownames_to_column('gene') %>%
    filter(s0 != 0, gene != '(Intercept)') %>%
    arrange(desc(abs(s0)));
  cors <- cor(df.drug.1()[input$drug], df.drug.1()[betas$gene]) %>%
    t();
  out <- cbind(betas, cors) %>%
    rename(beta = s0, cor = input$drug);
  rownames(out) <- NULL;
  head(out, 10);
});

output$betas <- renderTable({
  betas.cor();
});

all.cors <- reactive({
  all.cors <- cor(df.drug.1()[input$drug], df.drug.1()[-(1:4)]) %>% 
    t() %>% 
    as.matrix() %>% 
    as.data.frame() %>% 
    rownames_to_column('gene') %>% 
    #arrange(desc(abs(get(input$drug)))) %>% 
    rename(cor = input$drug) %>% 
    #head(10) %>% 
    merge(select(betas.cor(), -cor), by = 'gene', all.x = TRUE) %>% 
    arrange(desc(abs(cor))) %>% 
    head(10);
  all.cors[is.na(all.cors)] <- 0;
  all.cors;
});

output$all.cors <- renderTable({
  all.cors();
});

output$betas.plot <- renderPlot({
  ggplot(betas.cor(), aes(x = factor(betas.cor()$gene, levels = betas.cor()$gene))) +
    geom_line(aes(y = abs(beta), color = 'beta', group = 1)) +
    geom_line(aes(y = abs(cor), color = 'cor', group = 1)) +
    geom_point(aes(y = abs(beta), color = 'beta')) +
    geom_point(aes(y = abs(cor), color = 'cor')) +
    xlab('') + ylab('abs coef') +
    theme_bw() +
    scale_colour_hue(name = '') +
    theme(axis.text.x = element_text(angle = -45, vjust = 0));
});

output$betas.plot2 <- renderPlot({
  ggplot(all.cors(), aes(x = factor(all.cors()$gene, levels = all.cors()$gene))) +
    geom_line(aes(y = abs(beta), color = 'beta', group = 1)) +
    geom_line(aes(y = abs(cor), color = 'cor', group = 1)) +
    geom_point(aes(y = abs(beta), color = 'beta')) +
    geom_point(aes(y = abs(cor), color = 'cor')) +
    xlab('') + ylab('abs coef') +
    theme_bw() +
    scale_colour_hue(name = '') +
    theme(axis.text.x = element_text(angle = -45, vjust = 0));
});

output$scatter <- renderPlot({
  ggplot(df.drug.1(), aes(x = get(input$drug), y = get(input$gene))) +
    geom_point() +
    geom_smooth(method = lm) +
    xlab(input$drug) +
    ylab(input$gene)
});
```

```{r}
# deployApp(
#   appDir = './reports',
#   appFiles = c(
#     'drug.gene.dashboard.rmd',
#     'drug.gene.dashboard_cache',
#     'drug.gene.dashboard_data'
#     ),
#   appName = 'cancer-vulnerability-dashboard'
#   );
```

